name: Bug Report
description: File a bug report for the Fetch Hook package
title: '[Bug]: '
labels: ['Bug', 'Triage']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report for the Fetch Hook package!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? (Optional)
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the issue. Also, what did you expect to happen?
      placeholder: Describe the bug and what you expected...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Package Version
      description: What version of the Fetch Hook package are you using?
      options:
        - 1.0.0
      default: 1.0.0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What environments are you seeing the problem in?
      multiple: true
      options:
        - Node.js
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or error messages
      description: Please copy and paste any relevant log output or error messages. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
